INSERT INTO Products(Name, Cost) VALUES('Airpods',159.99);
INSERT INTO Products(Name, Cost) VALUES('Bubble Wrap',2.99);
INSERT INTO Products(Name, Cost) VALUES('Cabinet',149.99);
INSERT INTO Products(Name, Cost) VALUES('Dartboard',9.99);
INSERT INTO Products(Name, Cost) VALUES('Earphones',4.99);
INSERT INTO Products(Name, Cost) VALUES('Flowers',9.99);
INSERT INTO Products(Name, Cost) VALUES('Gift Card',10);
INSERT INTO Products(Name, Cost) VALUES('Highlighter',0.99);
INSERT INTO Products(Name, Cost) VALUES('iPhone',699.99);
INSERT INTO Products(Name, Cost) VALUES('Juicer',29.99);
INSERT INTO Products(Name, Cost) VALUES('Kettle',29.99);
INSERT INTO Products(Name, Cost) VALUES('Lego',24.99);
INSERT INTO Products(Name, Cost) VALUES('Memory Stick',9.99);
INSERT INTO Products(Name, Cost) VALUES('Nail File',3.99);
INSERT INTO Products(Name, Cost) VALUES('Office Chair',59.99);
INSERT INTO Products(Name, Cost) VALUES('Pillow',4.99);
INSERT INTO Products(Name, Cost) VALUES('Quinoa',3.99);
INSERT INTO Products(Name, Cost) VALUES('Rubiks Cube',6.99);
INSERT INTO Products(Name, Cost) VALUES('SD Card',11.99);
INSERT INTO Products(Name, Cost) VALUES('Tape Measure',5.99);
INSERT INTO Products(Name, Cost) VALUES('USB Cable',9.99);
INSERT INTO Products(Name, Cost) VALUES('Vacuum Cleaner',129.99);
INSERT INTO Products(Name, Cost) VALUES('Whiteboard',99.99);
INSERT INTO Products(Name, Cost) VALUES('Xbox One',299.99);
INSERT INTO Products(Name, Cost) VALUES('Yoga Mat',14.99);
INSERT INTO Products(Name, Cost) VALUES('Zip Tie',0.05);
